name: temp.yaml
on:
  push:
    branches:
      - master
jobs:
  bep:
    runs-on: PiServer
    steps:
      - name: Print a message
        run: echo "Hello from GitHub Actions! ${{ secrets.OSSRH_USERNAME }}"
